### PR TITLE
Preliminary commit of package build files

### PR DESCRIPTION
**Pull request by pantsman0**
This commit adds the file os-build/linux-rpm/sozu.spec providing an RPM
spec file, and os-build/config.toml.in providing a config file template.

### CODE REVIEW

**Comment by pantsman0** [comment]
Not sure what the best format for this is.

I've built a template config file and an RPM spec file to install sozu onto a fedora system.
This can be expanded using the RPM macro system to support other versions of Fedora/RedHat/CentOS, but it has only been tested on Fedora 25 so far.

Let me know if there are any changes you want to it such as: moving files to new locations, changing the macro engine for the config file, adding systemd/sysVinit service files.

It also addresses part of #161

**Comment by Geal** [comment]
This looks good! I don't know yet if the packaging should be in the same repository, though. I'd prefer a separate repository with all the packaging, but I don't know how cumbersome it would be.

We should probably make a way for the proxy to get his config file from `/etc/sozu` directly if not passed from the command line.

**Comment by pantsman0** [comment]
Packaging can be in a separate repo based on your preferences.

Regarding a default value:
For an installed package it can be provided with package files (e.g. `/etc/profile.d/sozu.sh` and `/etc/sysconfig/sozu` on RHEL/CentOS/Fedora systems) that can alias the command with the right default (e.g. `alias sozuctl='/usr/bin/sozuctl --config $((source /etc/sysconfig/sozu ; echo $sozu_config))`). With rpmbuild's macros this is pretty simple for rpm-based distributions, but may need some more work for other distros.

Setting a default value in the code should also be pretty easy for a static value.

Setting a default during the build will be a bit more difficult though. Looking at the rust docs, it looks like a using a build script `build.rs` would be the solution to this, but I'm not sure how this works in reality.

**Comment by pantsman0** [comment]
Something for `build.rs`: The build script can configure compile time variables, then the source files can use the `include!()` macro to include those variables in the binary.

This would mirror the effect of `include.h` in an autoconfigure project.

**Comment by Geal** [comment]
Could you add a script to generate the package?

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
