### PR TITLE
Fix a panic when parsing cookies

### PR DESCRIPTION
**Pull request by BlackYoup**
A panic could occur when parsing cookies if the `SOZUBALANCEID=X` was found at the end of the cookie chain. Some bytes would not be deleted from the request, leading 2 chars (`=X`) not consumed.

Those commits fix that and try to be a bit more smarter about bytes consumption

### CODE REVIEW

**Comment by Geal** [comment]
plz add unit tests for that kind of thing? Maybe that parser should be fuzzed a bit :)

**Comment by BlackYoup** [comment]
Here are some unit test. I'm not sure if it covers all cases but it would have catch that bug. Fuzzing would be cool indeed and I'll look into that, but it might not be before a few days / weeks.

**Comment by Geal** [comment]
up :)

**Comment by BlackYoup** [comment]
Sorry :D 

So, I started a fuzzing of the cookie parser but I'm not sure if I do it right. I use cargo-fuzz and you can find it here: https://github.com/BlackYoup/sozu/tree/cookie-parser-fuzzing

It's currently running since a few hours, I'll let it for a few days. But I feel like I'm not testing the right part of the code (more like the nom part) because I don't know if it ever will have the right input to pass the nom parsing ?

**Pull request merged**
