### PR TITLE
Issue 363 : Handle error in configuration for sozuctl & sozu

### PR DESCRIPTION
**Pull request by fteychene**
sozuctl : Change run for a safe run returning a Result and manage errors in the main to stop gracefully in case of error.

WIP :Should do the same thing for sozu

Fix issue #363

### CODE REVIEW

**Comment by fteychene** [comment]
Waiting #428 to use the same enum logic for Error if merged.
Also seems that this PR is doring the same thing for sozu command :smile:

**Comment by BlackYoup** [comment]
Oh yes, sorry, I didn't thought about this PR when I did mine :( The main function of sozu was upsetting me so hard I decided to rewrite it..

**Comment by fteychene** [comment]
No pb :smile: 
Just waiting for the use of enum for Error. I prefer that to what I've done but I hesitated.

If your PR is merged I will change mine to use enum for errors too :wink:

**Comment by Geal** [comment]
closing since the other PR apparently did it. Thank you for your help anyway :)

**Comment by BlackYoup** [comment]
@Geal I'm not sure that PR should be closed, it is for `sozuctl`, not `sozu` or I'm missing something here?

**Comment by fteychene** [comment]
Yes @BlackYoup this PR was for `sozuctl` not for `sozu` :smile:

**Pull request closed without merging**
