### PR TITLE
ci: rewritten the image building action

### PR DESCRIPTION
**Pull request by shanduur**
I tried to add some fixes to the CI, so the docker image is built and published (now to [GHCR](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)) correctly. This can be easily changed in the future, if GHCR does not meet the expectations.

The action should work as is, as it's mostly copy-pasted from my other project.

### CODE REVIEW

**Comment by shanduur** [comment]
One more thing - I added Dependabot config so the dependencies might be updated automatically, but this also needs to be turned on by admins here:
https://github.com/sozu-proxy/sozu/settings/security_analysis

**Comment by shanduur** [comment]
Drafting, because even if local build works for me, the GH Action is failing, need to debug it further.

**Comment by shanduur** [comment]
Ok, passed on my repo branch, should be good for review now 🔥

**Comment by Keksoj** [comment]
This looks very nice, thank you. I have no clue wether GHCR is better than docker hub for our needs.
Would you elaborate on the relevance of GHCR as opposed to Docker Hub ?

Thoughts on Github Container Repository vs Docker hub, @FlorentinDUBOIS ?

**Comment by shanduur** [comment]
I selected it only because you do not need to manage the credentials during the build process, rotate it, etc. It's just easily integrated into the whole flow.

**Comment by Gontier-Julien** [comment]
+1 for this so i can run it on docker 💯

**Comment by FlorentinDUBOIS** [comment]
Hello, we have another pull request that fix the ci without rewriting it, 
I have merged this one instead.
Besides, I am updating the credentials to be able to have the docker images available

**Pull request closed without merging**
