### PR TITLE
CI: Add sozu benchmark

### PR DESCRIPTION
**Pull request by GuillaumeASSIER**
Hi,

As sozu need strong performances, we need a simple way to benchmark sozu regularly.

I create a complete sozu benchmark script using python who's in charge of booting a sozu with lagging_server, load certificates with a complete configuration and run a stressing tool. At the end, we collect all the results in a log file archive as an artifact.

It's automated with a CI called benchmark.yml to automate the build and the benchmarking tool. For now, I use bombardier, but we can easily add new testing tools.

This setup test sozu performances with following settings :

- 1 Minute duration
- 400 connections at max
- HTTP1 (HTTP2 can be support if needed)
- HTTP Plain text
- HTTPS with the following encryption settings
  - RSA 2048
  - RSA 4096
  - ECDSA

The aim is not to get some reliable results, but to get a simple methodology that we can reuse in the future to track sozu performances.

### CODE REVIEW

**Comment by Keksoj** [comment]
please squash the commits and add a description to this PR to give context, list objectives, show some output examples.

**Comment by Keksoj** [comment]
I like it very much. Can you please remove the "draft" mention to the pull request?

Also, it would be great to have the output of the benchmark be displayed somewhere. The dream would be to have the same as the [rustls repository](https://github.com/rustls/rustls), where a [dedicated benchmarking bot](https://github.com/apps/rustls-benchmarking) is present and creates [nice tables of results](https://github.com/rustls/rustls/pull/1640#issuecomment-1854147668) at will.
At the very least, it would be cool to display the results in the output of the benchmark job.

**Review by Keksoj — APPROVED** [review]
looks awesome to me. Please squash everything :-)

**Comment by GuillaumeASSIER** [comment]
I failed to fix the git history. I made a new clean [PR](https://github.com/sozu-proxy/sozu/pull/1071)

**Pull request closed without merging**
