### PR TITLE
systemd: use RuntimeDir

### PR DESCRIPTION
**Pull request by Keruspe**
This has been the preferred way of dealing with this for quite some time now.

### CODE REVIEW

**Comment by Geal** [comment]
why delete the config file though?

**Comment by Keruspe** [comment]
Because the RuntimeDirectory directive is a drop-in (and more powerful) replacement to the tmpfiles config

**Comment by Geal** [comment]
can't we have a template for the configuration file stored somewhere?

**Comment by Keruspe** [comment]
Why would you want to keep it? It actually shouldn't have existed in the first place, that was just me using deprecated stuff

**Comment by Geal** [comment]
alright then

**Pull request merged**
