### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by Keksoj**
While searching the codebase for #644, I stumbled upon dead code and confusing comments. This PR removes the code and makes those few comments relevant.

### CODE REVIEW

**Comment by Geal** [comment]
This should not be removed: I deactivated it when refactoring the sessions but did not have the time to reactivate it.

The behaviour should be:
- if we reach the connection limit, stop accepting new connections and flush the accept queue, to signal quickly to clients that they should reconnect elsewhere
- wait until we recover some capacity before accepting again (otherwise it will spend its time stopping then accepting again)

**Comment by FlorentinDUBOIS** [comment]
Is the connection limit, the number of entry in the session slab ?

**Comment by Geal** [comment]
It should be the max number of slab elements, but:
- each socket listener takes one slab element
- a HTTP 1 session takes 1 or 2 slab elements
- a HTTP 2 session could take more than 2 slab elements

So the value will never be extremely precise, it depends on the usage

**Comment by FlorentinDUBOIS** [comment]
We will keep those code in the codebase until we will use it or refactor it

**Pull request closed without merging**
