### PR TITLE
[WIP] new buffering and HTTP message representation

### PR DESCRIPTION
**Pull request by Geal**
implementation for #596 

It rewrites `RequestState` and `ResponseState` to reduce the number of states and hold a list of headers containing references to offfsets in the network stream (not slices of the buffer to avoid issues with mutable borrows).

It is now easier to go through the header list and change them, add more (deletion not implemented yet)

### CODE REVIEW

**Comment by Keksoj** [comment]
Hi @Geal , what is your advancement about this? I will order it into the `0.14` milestone project, for convenience.

**Comment by Geal** [comment]
the architecture is done, it is missing header deletion (to avoid passing hop by hop headers between frontend and backend). It will need a lot of testing on real traffic before being production ready though

**Comment by Keksoj** [comment]
We've got to rebase this to see more clearly.

**Comment by Keksoj** [comment]
This is to be looked into, but we may want to implement HTTP2 beforehand, as is envisioned in the roadmap, before refactoring the state machine this much.

**Comment by Geal** [comment]
No, it's the other way: to implement http/2 you need an intermediate representation for the headers and a way to slice input buffers and transmit them between http 1 and 2. So that work was started to enable the http/2 implementation later.
If you try to implement http/2 first you will soon be blocked wondering how to translate between versions, and you'll go back to this PR 😄

**Comment by Keksoj** [comment]
ping @Wonshtrum

**Comment by Keksoj** [comment]
relevant commit is [b1c2ccc](https://github.com/sozu-proxy/sozu/pull/703/commits/b1c2ccc100bdb67f48b573ffdb4c42bf799781ab)

**Comment by Keksoj** [comment]
We close this PR because progress has been made with [kawa](https://github.com/CleverCloud/kawa), that will allow HTTP2.

This branch is usefull and will be kept as reference in the HTTP2 milestone.

**Pull request closed without merging**
