### PR TITLE
Add PKGBUILD for Archlinux systems

### PR DESCRIPTION
**Pull request by badboy**
Once #225 is merged this builds a package for Archlinux/pacman systems. I will also upload it to the [AUR](https://aur.archlinux.org/packages/sozu-git) then.
On systems with the necessary tools all that is required is `makepkg` in the directory.
It will use the latest git checkout.

### CODE REVIEW

**Comment by badboy** [comment]
As requested in #161

**Comment by Geal** [comment]
@badboy the PR on std::mem was merged, can you try again after a rebase?

**Comment by badboy** [comment]
I don't need to change anything in this PR to make it work, so feel free to merge away

**Comment by Geal** [comment]
great, thanks!

**Pull request merged**
