### PR TITLE
0.14 remove if let statements

### PR DESCRIPTION
**Pull request by Keksoj**
This started off as a the rewriting of certificate adding/removing/replacing logic, in the `ctl` module.

This went on to rewrite `if let` statements across the entirety of the Sōzu code, which is certainly a good idea, but still a lot of work.

### CODE REVIEW

**Comment by Geal** [comment]
while the code could look better in the end, it is really risky to do such a huge refactoring that changes large parts of tricky code all at once. This will introduce bugs that are hard to find. It would be a better idea to do that as a serie of smaller pull requests with intensive testing

**Comment by Keksoj** [comment]
Yeah, this went too far, I'm keep only the one or two first commits.

**Review by FlorentinDUBOIS — APPROVED** [review]

**Comment by FlorentinDUBOIS** [comment]
Could you keep only the commit [85045bd66a5ada03f7857fedca9ea50127a13346](https://github.com/sozu-proxy/sozu/pull/777/commits/85045bd66a5ada03f7857fedca9ea50127a13346) ?

**Comment by Keksoj** [comment]
Yep that's what I'll do, revert the others, request your review, squash everything, merge.

**Pull request merged**
