### PR TITLE
Remove unused whitespace functions from http parser.

### PR DESCRIPTION
**Pull request by bheesham**
This change is [Reviewable](https://reviewable.io/reviews/sozu-proxy/sozu/636)

### CODE REVIEW

**Comment by Geal** [comment]
oh, nice catch :)
This is dead code though, so maybe it would be better to change the PR to remove `is_ws`, `is_vchar_or_ws` and `vchar_ws_1`

**Comment by bheesham** [comment]
Haha thanks. 

Cool, I removed the functions you mentioned. Does the PR look good?

**Comment by Geal** [comment]
yes, thanks

**Comment by bheesham** [comment]
Thanks for the guidance :)

**Pull request merged**
